In [5]:
import numpy as np
print(np.cos(np.pi))
print(np.e + 1)

-1.0
3.718281828459045


In [4]:
a=3
b=-8.4
c='K'
d='I love you'
e=True
print(type(a)) #type은 이미 만들어진 변수의 종류를 확인시켜준다
print(type(b))
print(type(c))
print(type(d))
print(type(e))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>


In [11]:
import numpy as np
s = np.sin(np.pi/3)

print(s)

print(np.round(3.567, 1)) #3.567을 소수점 둘째 자리에서 반올림

print(np.round(decimals=1, a=3.567)) # decimals:소수자릿수, a:숫자를 의미하니까 순서를 바꿔도 그대로 출력

v = 3.14
print(f'value of v is {v}') #따옴표 앞에 f를 붙여 사용하면 변수의 값을 포함하는 새로운 문자열을 만듬

0.8660254037844386
3.6
3.6
value of v is 3.14


In [16]:
#3.7 고급 데이터 타입
vs1 = [1,3,'Hi',8.5]
vs2 = []
vs2.append(1)
vs2.append(3)
vs2.append('Hi')
vs2.append(8.5)
print(vs1)
print(vs2)
vs2.insert(2,1000) #리스트의 특정 위치에 항목 추가
print(vs2)
vs1.extend(vs2) #리스트 뒤에 다른 리스트를 덧붙임
print(vs1)
print()

#튜플은 수정할 수 없다(나머지는 리스트와 동일)
#대괄호 안쓰거나 소괄호 쓰면 된다. 아니면 리스트에 tuple()함수를 쓰던가
tup1 = 3,4,5
tup2 = (3,4,5)
my_list = [5,8,7]
tup3 = tuple(my_list)
print(tup1,tup2,tup3)
print()

#딕셔너리
#리스트와 비슷, 항목에 순서가 없고 각 항목에 이름이 붙는다는 차이
d1 = {'Title' : 'The Chronicles of Narnia',
      'Year' : 1950,
      'Author' : 'C. S. Lewis',
      'Country' : 'UK',
      'Genre' : 'Fantasy'}
print(d1['Title'])

[1, 3, 'Hi', 8.5]
[1, 3, 'Hi', 8.5]
[1, 3, 1000, 'Hi', 8.5]
[1, 3, 'Hi', 8.5, 1, 3, 1000, 'Hi', 8.5]
(3, 4, 5) (3, 4, 5) (5, 8, 7)
The Chronicles of Narnia


In [24]:
import numpy as np
n = np.array([3,4,1,2,8,2,4,9])
print(n)

n = np.array([[3,4,1,2],[8,2,4,9]])
print(n)

n = np.zeros((3,5))
m = np.ones((3,5,2))
print(n)
print(m)
n = np.random.rand(3,5)
print(n[1,2])

#np.expand_dims 함수
n = np.zeros(3)
print(n)
print(n.shape)
n = np.expand_dims(n,1) #1번 차원을 추가
print(n)
print(n.shape)

#reshape함수
n = np.array([3,4,1,2,8,2,4,9])
m = np.reshape(n,(2,4))
print(n)
print(m)
n.shape
m.shape


[3 4 1 2 8 2 4 9]
[[3 4 1 2]
 [8 2 4 9]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
0.26840359932295077
[0. 0. 0.]
(3,)
[[0.]
 [0.]
 [0.]]
(3, 1)
[3 4 1 2 8 2 4 9]
[[3 4 1 2]
 [8 2 4 9]]


(2, 4)

In [31]:
def add(v1,v2):
  #sum = v1 + v2
  #return sum
  #위와 동일 결과
  return v1 + v2

def add1(v1, v2=5):
  return v1 + v2

v = add(3,6)
v1 = add1(3)
print(v)
print(v1)

def change_var(arr):
  arr[0,0] = 999

d = np.random.rand(5,4)
print(f'함수호출 전 : {d[0,0]}')
change_var(d)
print(f'함수호출 후 : {d[0,0]}')

def change_var1(arr):
  arr = 999

d = np.random.rand(5,4)
print(f'before : {d[0,0]}')
change_var1(d)
print(f'after : {d[0,0]}') #여기서는 arr이 새로운 숫자 객체를 가리키니까 차이가 없다

9
8
함수호출 전 : 0.01589146579426237
함수호출 후 : 999.0
before : 0.8121726343663578
after : 0.8121726343663578
